<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       
            Country::create(['code' => 1, 'description' => ' N/A', 'deleted_at' => date('Y-m-d H:i:s')]);
            Country::create(['code' => 13, 'description' => ' AFGANISTAN']);
            Country::create(['code' => 248, 'description' => ' ALAND']);
            Country::create(['code' => 17, 'description' => ' ALBANIA']);
            Country::create(['code' => 23, 'description' => ' ALEMANIA']);
            Country::create(['code' => 26, 'description' => ' ARMENIA']);
            Country::create(['code' => 27, 'description' => ' ARUBA']);
            Country::create(['code' => 29, 'description' => ' BOSNIA HERZEGOVINA']);
            Country::create(['code' => 31, 'description' => ' BURKINA FASSO']);
            Country::create(['code' => 37, 'description' => ' ANDORRA']);
            Country::create(['code' => 40, 'description' => ' ANGOLA']);
            Country::create(['code' => 41, 'description' => ' ANGUILLA']);
            Country::create(['code' => 43, 'description' => ' ANTIGUA Y BARBUDA']);
            Country::create(['code' => 47, 'description' => ' ANTILLAS HOLANDESAS']);
            Country::create(['code' => 53, 'description' => ' ARABIA SAUDITA']);
            Country::create(['code' => 59, 'description' => ' ARGELIA']);
            Country::create(['code' => 63, 'description' => ' ARGENTINA']);
            Country::create(['code' => 69, 'description' => ' AUSTRALIA']);
            Country::create(['code' => 72, 'description' => ' AUSTRIA']);
            Country::create(['code' => 74, 'description' => ' AZERBAIJAN']);
            Country::create(['code' => 77, 'description' => ' BAHAMAS']);
            Country::create(['code' => 80, 'description' => ' BAHREIN']);
            Country::create(['code' => 81, 'description' => ' BANGLADESH']);
            Country::create(['code' => 83, 'description' => ' BARBADOS']);
            Country::create(['code' => 87, 'description' => ' BELGICA']);
            Country::create(['code' => 88, 'description' => ' BELICE']);
            Country::create(['code' => 90, 'description' => ' BERMUDAS']);
            Country::create(['code' => 91, 'description' => ' BELARUS']);
            Country::create(['code' => 93, 'description' => ' BIRMANIA MYANMAR']);
            Country::create(['code' => 97, 'description' => ' BOLIVIA']);
            Country::create(['code' => 101, 'description' => ' BOTSWANA']);
            Country::create(['code' => 105, 'description' => ' BRASIL']);
            Country::create(['code' => 108, 'description' => ' BRUNEI DARUSSALAM']);
            Country::create(['code' => 111, 'description' => ' BULGARIA']);
            Country::create(['code' => 115, 'description' => ' BURUNDI']);
            Country::create(['code' => 119, 'description' => ' BUTAN']);
            Country::create(['code' => 127, 'description' => ' CABO VERDE']);
            Country::create(['code' => 137, 'description' => ' ISLAS CAIMAN ']);
            Country::create(['code' => 141, 'description' => ' CAMBOYA KAMPUCHEA']);
            Country::create(['code' => 145, 'description' => ' REPUBLICA UNIDA DEL CAMERUN']);
            Country::create(['code' => 149, 'description' => ' CANADA']);
            Country::create(['code' => 159, 'description' => ' SANTA SEDE']);
            Country::create(['code' => 165, 'description' => ' ISLAS COCOS KEELING']);
            Country::create(['code' => 169, 'description' => ' COLOMBIA']);
            Country::create(['code' => 173, 'description' => ' COMORAS']);
            Country::create(['code' => 177, 'description' => ' CONGO']);
            Country::create(['code' => 183, 'description' => ' ISLAS COOK']);
            Country::create(['code' => 187, 'description' => ' REPUBLICA POPULAR DEMOCRATICA DE COREA NORTE']);
            Country::create(['code' => 190, 'description' => ' REPUBLICA DE COREA SUR']);
            Country::create(['code' => 193, 'description' => ' COSTA DE MARFIL']);
            Country::create(['code' => 196, 'description' => ' COSTA RICA']);
            Country::create(['code' => 198, 'description' => ' CROACIA']);
            Country::create(['code' => 199, 'description' => ' CUBA']);
            Country::create(['code' => 203, 'description' => ' CHAD']);
            Country::create(['code' => 211, 'description' => ' CHILE']);
            Country::create(['code' => 215, 'description' => ' CHINA']);
            Country::create(['code' => 218, 'description' => ' TAIWAN FORMOSA']);
            Country::create(['code' => 221, 'description' => ' CHIPRE']);
            Country::create(['code' => 229, 'description' => ' BENIN']);
            Country::create(['code' => 232, 'description' => ' DINAMARCA']);
            Country::create(['code' => 235, 'description' => ' DOMINICA']);
            Country::create(['code' => 239, 'description' => ' ECUADOR']);
            Country::create(['code' => 240, 'description' => ' EGIPTO']);
            Country::create(['code' => 242, 'description' => ' EL SALVADOR']);
            Country::create(['code' => 243, 'description' => ' ERITREA']);
            Country::create(['code' => 244, 'description' => ' EMIRATOS ARABES UNIDOS']);
            Country::create(['code' => 245, 'description' => ' ESPAÑA']);
            Country::create(['code' => 246, 'description' => ' ESLOVAQUIA']);
            Country::create(['code' => 247, 'description' => ' ESLOVENIA']);
            Country::create(['code' => 249, 'description' => ' ESTADOS UNIDOS']);
            Country::create(['code' => 251, 'description' => ' ESTONIA']);
            Country::create(['code' => 253, 'description' => ' ETIOPIA']);
            Country::create(['code' => 259, 'description' => ' ISLAS FEROE']);
            Country::create(['code' => 267, 'description' => ' FILIPINAS']);
            Country::create(['code' => 271, 'description' => ' FINLANDIA']);
            Country::create(['code' => 275, 'description' => ' FRANCIA']);
            Country::create(['code' => 281, 'description' => ' GABON']);
            Country::create(['code' => 285, 'description' => ' GAMBIA']);
            Country::create(['code' => 287, 'description' => ' GEORGIA']);
            Country::create(['code' => 289, 'description' => ' GHANA']);
            Country::create(['code' => 293, 'description' => ' GIBRALTAR']);
            Country::create(['code' => 297, 'description' => ' GRANADA']);
            Country::create(['code' => 301, 'description' => ' GRECIA']);
            Country::create(['code' => 305, 'description' => ' GROENLANDIA']);
            Country::create(['code' => 309, 'description' => ' GUADALUPE']);
            Country::create(['code' => 313, 'description' => ' GUAM']);
            Country::create(['code' => 317, 'description' => ' GUATEMALA']);
            Country::create(['code' => 325, 'description' => ' GUAYANA FRANCESA']);
            Country::create(['code' => 329, 'description' => ' GUINEA']);
            Country::create(['code' => 331, 'description' => ' GUINEA ECUATORIAL']);
            Country::create(['code' => 334, 'description' => ' GUINEA BISSAU']);
            Country::create(['code' => 337, 'description' => ' GUYANA']);
            Country::create(['code' => 341, 'description' => ' HAITI']);
            Country::create(['code' => 345, 'description' => ' HONDURAS']);
            Country::create(['code' => 351, 'description' => ' HONG KONG']);
            Country::create(['code' => 355, 'description' => ' HUNGRIA']);
            Country::create(['code' => 361, 'description' => ' INDIA']);
            Country::create(['code' => 365, 'description' => ' INDONESIA']);
            Country::create(['code' => 369, 'description' => ' IRAK']);
            Country::create(['code' => 372, 'description' => ' REPUBLICA ISLAMICA DEL IRAN']);
            Country::create(['code' => 375, 'description' => ' IRLANDA EIRE']);
            Country::create(['code' => 379, 'description' => ' ISLANDIA']);
            Country::create(['code' => 383, 'description' => ' ISRAEL']);
            Country::create(['code' => 386, 'description' => ' ITALIA']);
            Country::create(['code' => 391, 'description' => ' JAMAICA']);
            Country::create(['code' => 399, 'description' => ' JAPON']);
            Country::create(['code' => 403, 'description' => ' JORDANIA']);
            Country::create(['code' => 406, 'description' => ' KAZAJSTAN']);
            Country::create(['code' => 410, 'description' => ' KENIA']);
            Country::create(['code' => 411, 'description' => ' KIRIBATI']);
            Country::create(['code' => 412, 'description' => ' KIRGUIZISTAN']);
            Country::create(['code' => 413, 'description' => ' KUWAIT']);
            Country::create(['code' => 420, 'description' => ' REPUBLICA POPULAR DEMOCRATICA DE LAOS']);
            Country::create(['code' => 426, 'description' => ' LESOTHO']);
            Country::create(['code' => 429, 'description' => ' LETONIA']);
            Country::create(['code' => 431, 'description' => ' LIBANO']);
            Country::create(['code' => 434, 'description' => ' LIBERIA']);
            Country::create(['code' => 438, 'description' => ' LIBIA INCLUYE FEZZAN']);
            Country::create(['code' => 440, 'description' => ' LIECHTENSTEIN']);
            Country::create(['code' => 443, 'description' => ' LITUANIA']);
            Country::create(['code' => 445, 'description' => ' LUXEMBURGO']);
            Country::create(['code' => 447, 'description' => ' MACAO']);
            Country::create(['code' => 448, 'description' => ' MACEDONIA']);
            Country::create(['code' => 450, 'description' => ' MADAGASCAR']);
            Country::create(['code' => 455, 'description' => ' MALAYSIA']);
            Country::create(['code' => 458, 'description' => ' MALAWI']);
            Country::create(['code' => 461, 'description' => ' MALDIVAS']);
            Country::create(['code' => 464, 'description' => ' MALI']);
            Country::create(['code' => 467, 'description' => ' MALTA']);
            Country::create(['code' => 469, 'description' => ' ISALAS MARIANAS DEL NORTE']);
            Country::create(['code' => 472, 'description' => ' ISLAS MARSHALL']);
            Country::create(['code' => 474, 'description' => ' MARRUECOS']);
            Country::create(['code' => 477, 'description' => ' MARTINICA']);
            Country::create(['code' => 485, 'description' => ' MAURICIO']);
            Country::create(['code' => 488, 'description' => ' MAURITANIA']);
            Country::create(['code' => 493, 'description' => ' MEXICO']);
            Country::create(['code' => 494, 'description' => ' ESTADOS FEDERADOS DE MICRONESIA']);
            Country::create(['code' => 496, 'description' => ' MOLDAVIA']);
            Country::create(['code' => 497, 'description' => ' MONGOLIA']);
            Country::create(['code' => 498, 'description' => ' MONACO']);
            Country::create(['code' => 501, 'description' => ' ISLA MONSERRAT']);
            Country::create(['code' => 505, 'description' => ' MOZAMBIQUE']);
            Country::create(['code' => 507, 'description' => ' NAMIBIA']);
            Country::create(['code' => 508, 'description' => ' NAURU']);
            Country::create(['code' => 511, 'description' => ' ISLAS NAVIDAD CHRISTMAS']);
            Country::create(['code' => 517, 'description' => ' NEPAL']);
            Country::create(['code' => 521, 'description' => ' NICARAGUA']);
            Country::create(['code' => 525, 'description' => ' NIGER']);
            Country::create(['code' => 528, 'description' => ' NIGERIA']);
            Country::create(['code' => 531, 'description' => ' ISLA NIUE']);
            Country::create(['code' => 535, 'description' => ' ISLA NORFOLK']);
            Country::create(['code' => 538, 'description' => ' NORUEGA']);
            Country::create(['code' => 542, 'description' => ' NUEVA CALEDONIA']);
            Country::create(['code' => 545, 'description' => ' NUEVA GUINEA PAPUASIA']);
            Country::create(['code' => 548, 'description' => ' NUEVA ZELANDIA']);
            Country::create(['code' => 551, 'description' => ' VANUATU']);
            Country::create(['code' => 556, 'description' => ' OMAN']);
            Country::create(['code' => 566, 'description' => ' ISLAS PACIFICO USA']);
            Country::create(['code' => 573, 'description' => ' descripcionES BAJOS HOLANDA']);
            Country::create(['code' => 576, 'description' => ' PAKISTAN']);
            Country::create(['code' => 578, 'description' => ' ISLA PALAU']);
            Country::create(['code' => 580, 'description' => ' PANAMA']);
            Country::create(['code' => 586, 'description' => ' PARAGUAY']);
            Country::create(['code' => 589, 'description' => ' PERU']);
            Country::create(['code' => 593, 'description' => ' ISLA PITCAIRN']);
            Country::create(['code' => 599, 'description' => ' POLINESIA FRANCESA']);
            Country::create(['code' => 603, 'description' => ' POLONIA']);
            Country::create(['code' => 607, 'description' => ' PORTUGAL']);
            Country::create(['code' => 611, 'description' => ' PUERTO RICO']);
            Country::create(['code' => 618, 'description' => ' QATAR']);
            Country::create(['code' => 628, 'description' => ' REINO UNIDO']);
            Country::create(['code' => 640, 'description' => ' REPUBLICA CENTROAFRICANA']);
            Country::create(['code' => 644, 'description' => ' REPUBLICA CHECA']);
            Country::create(['code' => 647, 'description' => ' REPUBLICA DOMINICANA']);
            Country::create(['code' => 660, 'description' => ' REUNION']);
            Country::create(['code' => 665, 'description' => ' ZIMBABWE']);
            Country::create(['code' => 670, 'description' => ' RUMANIA']);
            Country::create(['code' => 675, 'description' => ' RUANDA']);
            Country::create(['code' => 676, 'description' => ' RUSIA']);
            Country::create(['code' => 677, 'description' => ' ISLAS SALOMON']);
            Country::create(['code' => 685, 'description' => ' SAHARA OCCIDENTAL']);
            Country::create(['code' => 687, 'description' => ' SAMOA']);
            Country::create(['code' => 690, 'description' => ' SAMOA NORTEAMERICANA']);
            Country::create(['code' => 695, 'description' => ' SAN CRISTOBAL Y NIEVES']);
            Country::create(['code' => 697, 'description' => ' SAN MARINO']);
            Country::create(['code' => 700, 'description' => ' SAN PEDRO Y MIGUELON']);
            Country::create(['code' => 705, 'description' => ' SAN VICENTE Y LAS GRANADINAS']);
            Country::create(['code' => 710, 'description' => ' SANTA ELENA']);
            Country::create(['code' => 715, 'description' => ' SANTA LUCIA']);
            Country::create(['code' => 720, 'description' => ' SANTO TOME Y PRINCIPE']);
            Country::create(['code' => 728, 'description' => ' SENEGAL']);
            Country::create(['code' => 731, 'description' => ' SEYCHELLES']);
            Country::create(['code' => 735, 'description' => ' SIERRA LEONA']);
            Country::create(['code' => 741, 'description' => ' SINGAPUR']);
            Country::create(['code' => 744, 'description' => ' REPUBLICA ARABE DE SIRIA']);
            Country::create(['code' => 748, 'description' => ' SOMALIA']);
            Country::create(['code' => 750, 'description' => ' SRI LANKA']);
            Country::create(['code' => 756, 'description' => ' REPUBLICA DE SUDAFRICA']);
            Country::create(['code' => 759, 'description' => ' SUDAN']);
            Country::create(['code' => 764, 'description' => ' SUECIA']);
            Country::create(['code' => 767, 'description' => ' SUIZA']);
            Country::create(['code' => 770, 'description' => ' SURINAM']);
            Country::create(['code' => 773, 'description' => ' SWAZILANDIA']);
            Country::create(['code' => 774, 'description' => ' TADJIKISTAN']);
            Country::create(['code' => 776, 'description' => ' TAILANDIA']);
            Country::create(['code' => 780, 'description' => ' REPUBLICA UNIDA DE TANZANIA']);
            Country::create(['code' => 783, 'description' => ' DJIBOUTI']);
            Country::create(['code' => 787, 'description' => ' TERRITORIO BRITANICO DEL OCEANO INDICO']);
            Country::create(['code' => 788, 'description' => ' TIMOR DEL ESTE']);
            Country::create(['code' => 800, 'description' => ' TOGO']);
            Country::create(['code' => 805, 'description' => ' TOKELAU']);
            Country::create(['code' => 810, 'description' => ' TONGA']);
            Country::create(['code' => 815, 'description' => ' TRINIDAD Y TOBAGO']);
            Country::create(['code' => 820, 'description' => ' TUNICIA']);
            Country::create(['code' => 823, 'description' => ' ISALAS TURCAS Y CAICOS']);
            Country::create(['code' => 825, 'description' => ' TURKMENISTAN']);
            Country::create(['code' => 827, 'description' => ' TURQUIA']);
            Country::create(['code' => 828, 'description' => ' TUVALU']);
            Country::create(['code' => 830, 'description' => ' UCRANIA']);
            Country::create(['code' => 833, 'description' => ' UGANDA']);
            Country::create(['code' => 845, 'description' => ' URUGUAY']);
            Country::create(['code' => 847, 'description' => ' UZBEKISTAN']);
            Country::create(['code' => 850, 'description' => ' VENEZUELA']);
            Country::create(['code' => 855, 'description' => ' VIET NAM']);
            Country::create(['code' => 863, 'description' => ' ISLAS VIRGENES BRITANICAS']);
            Country::create(['code' => 866, 'description' => ' ISLAS VIRGENES NORTEAMERICANAS']);
            Country::create(['code' => 870, 'description' => ' FIJI']);
            Country::create(['code' => 875, 'description' => ' ISLAS WALLIS Y FORTUNA']);
            Country::create(['code' => 880, 'description' => ' YEMEN']);
            Country::create(['code' => 885, 'description' => ' YUGOSLAVIA']);
            Country::create(['code' => 888, 'description' => ' ZAIRE']);
            Country::create(['code' => 890, 'description' => ' ZAMBIA']);
            Country::create(['code' => 897, 'description' => ' ZONA NEUTRAL PALESTINA']);
        
    }
}
